import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/contexts/UserContext";
import { WorkspaceProvider } from "@/contexts/WorkspaceContext";
import {
  ClerkProvider,
  // SignInButton,
  SignedIn,
  // SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { ThemeProvider } from "@/contexts/ThemeContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <UserProvider>
        <WorkspaceProvider>
          <ThemeProvider>
            <html lang="en">
              <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
              >
                {/* <SignedOut>
            <SignInButton />
            </SignedOut> */}
                <SignedIn>
                  <UserButton />
                </SignedIn>
                {/* <Component {...pageProps} /> */}
                {children}
              </body>
            </html>
          </ThemeProvider>
        </WorkspaceProvider>
      </UserProvider>
    </ClerkProvider>
  );
}
